### ISSUE TITLE
cant run uddup

### ISSUE THREAD

**Issue by siratsami** [rotemreiss/uddup#9]
This tool is so great and really useful but i have noticed you will move the uddup execute script to /usr/local/bin directory which is actually doesnt work some times because its needs to be in /usr/bin directory to be executed i dont know why...
I copied the script to /usr/bin and its worked perfectly.
Im using kali linux subsystem on windows 11.
Sorry if theres a problem with my issue report, its my first issue report on github :V 
Thanks.

**Comment by rotemplay** [comment]
Hey @siratsami,
How did you install uddup? You don't need to move it anywhere or do anything except for running `pip install uddup`.
Once installed, uddup should automatically add itself as an executable to your PATH (this is due to the built-in mechanism of Python packages, as defined in https://github.com/rotemreiss/uddup/blob/master/setup.py).

**Comment by rotemreiss** [comment]
Hey @siratsami,
How did you install uddup? You don't need to move it anywhere or do anything except for running pip install uddup.
Once installed, uddup should automatically add itself as an executable to your PATH (this is due to the built-in mechanism of Python packages, as defined in https://github.com/rotemreiss/uddup/blob/master/setup.py).

**Comment by rotemreiss** [comment]
Closing as there was no update from the user.
